import { EnvMap } from "../parser/envParser";

export type FormatStyle = "dotenv" | "export" | "json" | "yaml" | "table";

export interface FormatOptions {
  style: FormatStyle;
  includeComments?: boolean;
  indent?: number;
}

export interface FormatResult {
  content: string;
  style: FormatStyle;
  lineCount: number;
}

export function formatAsDotenv(map: EnvMap, includeComments = false): string {
  const lines: string[] = [];
  if (includeComments) lines.push("# Generated by stackdiff");
  for (const [key, value] of map.entries()) {
    const needsQuotes = /\s|#|=/.test(value);
    lines.push(`${key}=${needsQuotes ? `"${value}"` : value}`);
  }
  return lines.join("\n");
}

export function formatAsExport(map: EnvMap): string {
  const lines: string[] = [];
  for (const [key, value] of map.entries()) {
    const needsQuotes = /\s|#|=/.test(value);
    lines.push(`export ${key}=${needsQuotes ? `"${value}"` : value}`);
  }
  return lines.join("\n");
}

export function formatAsYaml(map: EnvMap, indent = 2): string {
  const pad = " ".repeat(indent);
  const lines: string[] = ["env:"];
  for (const [key, value] of map.entries()) {
    const needsQuotes = /[:#{}\[\],&*?|<>=!%@`]/.test(value) || value === "";
    lines.push(`${pad}${key}: ${needsQuotes ? `"${value}"` : value}`);
  }
  return lines.join("\n");
}

export function formatAsTable(map: EnvMap): string {
  const entries = Array.from(map.entries());
  if (entries.length === 0) return "(empty)";
  const maxKey = Math.max(3, ...entries.map(([k]) => k.length));
  const maxVal = Math.max(5, ...entries.map(([, v]) => v.length));
  const sep = `+${"-".repeat(maxKey + 2)}+${"-".repeat(maxVal + 2)}+`;
  const header = `| ${"KEY".padEnd(maxKey)} | ${"VALUE".padEnd(maxVal)} |`;
  const rows = entries.map(
    ([k, v]) => `| ${k.padEnd(maxKey)} | ${v.padEnd(maxVal)} |`
  );
  return [sep, header, sep, ...rows, sep].join("\n");
}

export function formatEnvMap(map: EnvMap, options: FormatOptions): FormatResult {
  let content: string;
  switch (options.style) {
    case "export": content = formatAsExport(map); break;
    case "yaml":   content = formatAsYaml(map, options.indent ?? 2); break;
    case "table":  content = formatAsTable(map); break;
    case "json":   content = JSON.stringify(Object.fromEntries(map), null, options.indent ?? 2); break;
    default:       content = formatAsDotenv(map, options.includeComments); break;
  }
  return { content, style: options.style, lineCount: content.split("\n").length };
}
