import { toTemplate, formatTemplate, mergeWithTemplate } from "./envTemplater";

function makeMap(obj: Record<string, string>): Map<string, string> {
  return new Map(Object.entries(obj));
}

describe("toTemplate", () => {
  it("replaces values with empty placeholder by default", () => {
    const m = makeMap({ FOO: "bar", BAZ: "qux" });
    const t = toTemplate(m);
    expect(t.get("FOO")).toBe("");
    expect(t.get("BAZ")).toBe("");
  });

  it("uses custom placeholder", () => {
    const m = makeMap({ FOO: "bar" });
    const t = toTemplate(m, { placeholder: "CHANGE_ME" });
    expect(t.get("FOO")).toBe("CHANGE_ME");
  });

  it("keeps values when includeValues is true", () => {
    const m = makeMap({ FOO: "bar" });
    const t = toTemplate(m, { includeValues: true });
    expect(t.get("FOO")).toBe("bar");
  });
});

describe("formatTemplate", () => {
  it("includes header comment and key=value lines", () => {
    const m = makeMap({ FOO: "", BAR: "" });
    const out = formatTemplate(m);
    expect(out).toContain("Generated by stackdiff");
    expect(out).toContain("FOO=");
    expect(out).toContain("BAR=");
  });

  it("uses custom comment prefix", () => {
    const m = makeMap({ X: "" });
    const out = formatTemplate(m, { commentPrefix: "// " });
    expect(out).toContain("// Generated");
  });
});

describe("mergeWithTemplate", () => {
  it("fills template keys with base values", () => {
    const base = makeMap({ FOO: "hello", EXTRA: "ignored" });
    const template = makeMap({ FOO: "", BAR: "" });
    const result = mergeWithTemplate(base, template);
    expect(result.get("FOO")).toBe("hello");
    expect(result.get("BAR")).toBe("");
    expect(result.has("EXTRA")).toBe(false);
  });

  it("does not add keys not in template", () => {
    const base = makeMap({ NEW_KEY: "val" });
    const template = makeMap({ OLD_KEY: "" });
    const result = mergeWithTemplate(base, template);
    expect(result.has("NEW_KEY")).toBe(false);
  });
});
