/**
 * envTemplater: generate .env template files from existing env maps
 * (keys only, values replaced with placeholders or type hints)
 */

export type TemplateOptions = {
  placeholder?: string;
  includeValues?: boolean;
  commentPrefix?: string;
};

const DEFAULT_OPTIONS: TemplateOptions = {
  placeholder: "",
  includeValues: false,
  commentPrefix: "# ",
};

export function toTemplate(
  envMap: Map<string, string>,
  options: TemplateOptions = {}
): Map<string, string> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const result = new Map<string, string>();
  for (const [key, value] of envMap) {
    result.set(key, opts.includeValues ? value : (opts.placeholder ?? ""));
  }
  return result;
}

export function formatTemplate(
  templateMap: Map<string, string>,
  options: TemplateOptions = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const lines: string[] = [
    `${opts.commentPrefix}Generated by stackdiff`,
    `${opts.commentPrefix}Fill in values before use`,
    "",
  ];
  for (const [key, value] of templateMap) {
    lines.push(`${key}=${value}`);
  }
  return lines.join("\n");
}

export function mergeWithTemplate(
  base: Map<string, string>,
  template: Map<string, string>
): Map<string, string> {
  const result = new Map(template);
  for (const [key, value] of base) {
    if (result.has(key)) {
      result.set(key, value);
    }
  }
  return result;
}
